Implement Mailchimp signup
mitodl/hugo-course-publisher pull request #298
Opened 2020-11-04 21:28 UTC by noisecapella

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fixes #283 

#### What's this PR do?
Implements mailchimp signup. We need to add `MAILCHIMP_USER_ID` and `MAILCHIMP_AUDIENCE_ID` environment variables to make this work and have them be present when hugo is run.

#### How should this be manually tested?
- Create a mailchimp account and get the user and audience ID. You can find these by going to the mailchimp dashboard and then clicking on Audience => Signup Forms => Embedded Forms => Condensed, for example. In the `action` attribute of `form` there is a url. The `u=` part is the user id and the `id=` is the audience id.
 - Set these values to `MAILCHIMP_USER_ID` and `MAILCHIMP_AUDIENCE_ID` in `.env`
 - Run `docker-compose up`
 - Fill out the email signup form at the bottom. You should see a success message or some variety of failure message.
 - You should be able to both press enter to submit and click the 'Sign me up' button.

#### Other context
This uses an undocumented feature I found on stackoverflow. I can't find anything about `post-json` on mailchimp's site. Hopefully it's reliable? https://stackoverflow.com/questions/8425701/ajax-mailchimp-signup-form-integration

#### Screenshots (if appropriate)
The empty form: ![Screenshot from 2020-11-04 16-24-51](https://user-images.githubusercontent.com/863262/98169481-4ed0f700-1eba-11eb-92ce-11bcb505b04c.png)

After filling out and submitting the form, you should see this:
![Screenshot from 2020-11-04 16-13-44](https://user-images.githubusercontent.com/863262/98169523-6e681f80-1eba-11eb-9319-ac3ecd902fff.png)

If you're already subscribed:
![Screenshot from 2020-11-04 16-14-12](https://user-images.githubusercontent.com/863262/98169542-745e0080-1eba-11eb-8085-958c81240130.png)

If you didn't type in a valid email:
![Screenshot from 2020-11-04 16-16-01](https://user-images.githubusercontent.com/863262/98169559-7c1da500-1eba-11eb-9330-b93756a6aa39.png)

These messages come from Mailchimp's response.

2020-11-05 20:44 UTC, mbertrand requested changes

2020-11-05 20:44 UTC, mbertrand commented on src/js/mailchimp.js
> +      $form.html(msg)
This replaces the input with the error message, preventing the user from correcting a mistake.  Can it be appended underneath the input instead?

<img width="616" alt="Screen Shot 2020-11-05 at 3 43 02 PM" src="https://user-images.githubusercontent.com/187676/98294312-c0be4480-1f7d-11eb-8b50-874c5b739af1.png">

2020-11-05 22:34 UTC, noisecapella commented
How is this?
![Screenshot from 2020-11-05 17-33-24](https://user-images.githubusercontent.com/863262/98303983-19e1a480-1f8d-11eb-935c-4e519e642dcc.png)

![Screenshot from 2020-11-05 17-33-46](https://user-images.githubusercontent.com/863262/98303986-1c43fe80-1f8d-11eb-83d7-e060fc6b65c8.png)

2020-11-06 13:47 UTC, mbertrand reviewed
A couple minor things:

- If I enter an invalid email with no '@', the error message from mailchimp starts with a "0 - ".  This error message is coming from mailchimp so I don't know if it's worth stripping that out or not since it may change in the future.
- The entire submit button appears to be clickable, but it is only submitted if I click directly over the "SIGN ME UP" text.

2020-11-06 16:33 UTC, mbertrand approved these changes
👍

2020-11-06 16:34 UTC, noisecapella commented
@mbertrand per our meeting I'm going to convert the jQuery code to pure javascript before merging

2020-11-06 22:30 UTC, noisecapella commented
@mbertrand on second thought I'm going to leave it in for now. Someone can fix this in #316. It seems nontrivial to replace the cross domain ajax hack that jquery uses, though there's probably a library somewhere to do it.

2020-11-06 22:30 UTC, merged