[testing] github actions for netlify, google pagespeed
mitodl/hugo-course-publisher pull request #430
Opened 2020-12-07 14:54 UTC by aliceriot

…erwards

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

2020-12-09 18:08 UTC, pdpinch commented
Looks like useful information. And looks like we have some work to do improving things.

2020-12-11 22:21 UTC, noisecapella requested changes

2020-12-11 22:21 UTC, noisecapella commented on .github/workflows/deploy.yml
> +    runs-on: ubuntu-18.04
Can we make this 20.04?

2020-12-14 14:16 UTC, aliceriot commented on .github/workflows/deploy.yml
> +    runs-on: ubuntu-18.04
good catch, I'll do `ubuntu-latest`

2020-12-14 14:19 UTC, noisecapella approved these changes

2020-12-14 14:51 UTC, merged